driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.0.3
  data_path: test/shared

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: debian-7.7
    run_list:
      - recipe[apt]
  - name: centos-6.6
    run_list:
      - recipe[yum::default]
  - name: centos-7.0
    run_list:
      - recipe[yum::default]

suites:
  - name: default
    run_list:
        - recipe[prometheus::default]
    attributes:

  - name: init
    run_list:
        - recipe[prometheus::default]
    attributes:
      prometheus:
        init_style: 'init'

  - name: bluepill
    run_list:
        - recipe[prometheus::default]
    attributes:
      prometheus:
        init_style: 'bluepill'

  - name: default-binary
    run_list:
        - recipe[prometheus::default]
    attributes:
      prometheus:
        install_method: 'binary'

  - name: init-binary
    run_list:
        - recipe[prometheus::default]
    attributes:
      prometheus:
        init_style: 'init'
        install_method: 'binary'
        flags:
          storage.remote.timeout: 45s

  - name: bluepill-binary
    run_list:
        - recipe[prometheus::default]
    attributes:
      prometheus:
        init_style: 'bluepill'
        install_method: 'binary'
